### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by JCassio1** [nogueiraantonio/dscpe-widget-property-editor#3]
I am currently trying to learn how to create 3DX widgets with Vue.js

Unfortunately, the documentation has not been very helpful as I do not have access to files to build one via the "Defining an additional app" method.

I have the following error log:

```
PS C:\SoftwareDev\3dExperience\dscpe-widget-property-editor> npm run start

> dscpe-cascade-selection@1.0.0 start
> webpack-dev-server --config ./webpack/webpack.config.dev.js --open

## There is an issue with `node-fibers` ##
`C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\fibers\bin\win32-x64-108\fibers.node` is missing.

Try running this to fix the issue: C:\Program Files\nodejs\node.exe C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\fibers/build
Error: Cannot find module 'C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\fibers\bin\win32-x64-108\fibers'
Require stack:
- C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\fibers\fibers.js
- C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\webpack\webpack.config.common.js
- C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\webpack\webpack.config.dev.js
- C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\webpack-cli\bin\utils\convert-argv.js
- C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\fibers\fibers.js:14:39)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\webpack\webpack.config.common.js:54:40)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\fibers\fibers.js:23
                throw new Error('Missing binary. See message above.');
                ^

Error: Missing binary. See message above.
    at Object.<anonymous> (C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\node_modules\fibers\fibers.js:23:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\webpack\webpack.config.common.js:54:40)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\SoftwareDev\3dExperience\dscpe-widget-property-editor\webpack\webpack.config.dev.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```

Are there any suggestions or resources to circumnavigate this?

Many thanks

**Comment by sangram2210** [comment]
Which is the release level?
